services:

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'app'
    env_file:
      - .env
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - pg_db
    volumes:
      - .:/app

  pg_db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
    postgres_data: